[package]
name = "sub-player"
version = "0.1.0"
description = "A modern, AI-powered subtitle player"
authors = ["you"]
license = "MIT"
repository = "https://github.com/micropsy/subplayer.git"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-http = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["stream"] }
futures-util = "0.3"
zip = { version = "2.1", default-features = false, features = ["deflate"] }
whisper-rs = { version = "0.12", optional = true }
uuid = { version = "1.0", features = ["v4", "serde"] }
directories-next = "2.0"
flate2 = "1.0"
tar = "0.4"
regex = "1.10"
hound = "3.5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
whisper = ["whisper-rs"]
